[project]
name = "shop-admin-bot-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.24.0",
    "httpx>=0.28.1",
    "pydantic-settings>=2.12.0",
    "ruff>=0.14.14",
]
